DROP DATABASE IF EXISTS `kampus_db`;
CREATE DATABASE IF NOT EXISTS `kampus_db`;
USE `kampus_db`;

DROP TABLE IF EXISTS `mahasiswa`;
CREATE TABLE IF NOT EXISTS mahasiswa (
    id INT AUTO_INCREMENT PRIMARY KEY,
    nama VARCHAR(100) NOT NULL,
    jurusan VARCHAR(100) NOT NULL,
    created_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4;
